### ISSUE TITLE
Map not working

### ISSUE THREAD

**Issue by sd-evo** [laravel-admin-extensions/latlong#32]
Site on local.
PHP: 7.3
Laravel: v7.2.2
Laravel-admin: v1.8.2

Method Encore\Admin\Latlong\Latlong::zoom does not exist.

```php
$form->latlong('content->lat', 'content->lon', 'Position')->zoom(5);
```

If use:
```php
$form->latlong('content->lat', 'content->lon', 'Местоположение')->default(['zoom' => 5]);
```
Then:

![Снимок экрана от 2020-09-02 21-07-58](https://user-images.githubusercontent.com/66308935/92020170-68da4600-ed60-11ea-9599-68c4e4b38c3a.png)

In config/admin.php:
```php
'extensions' => [
        'latlong' => [
            'enable' => true,
            'default' => 'yandex',
            'providers' => [
                'google' => [
                    'api_key' => env('GOOGLE_MAP_API_KEY'),
                ],
                'yandex' => [
                    'api_key' => env('YANDEX_MAP_API_KEY'),
                ],
            ]
        ],
    ],
```

**Comment by jeff-forest** [comment]
https://github.com/laravel-admin-extensions/latlong/pull/31 <--  zishang520 commented yesterday for fixes

**Comment by sd-evo** [comment]
@jeff-forest omg, thx :+1: 
@z-song please, see #31

**Comment by sd-evo** [comment]
@z-song thx :+1:
