### ISSUE TITLE
Laravel Admin 2.0 support?

### ISSUE THREAD

**Issue by vlados** [laravel-admin-extensions/latlong#36]
What is needed to make the extension supported for the new major version of Laravel Admin?

**Comment by z-song** [comment]
Need to develop a new version to be compatible with laravel-admin 2.0

**Comment by vlados** [comment]
Can I help? Is it only to update composer.json or it needs some more work to be done?

**Comment by z-song** [comment]
@vlados Now it supports laravel-admin 2.0, the code modification is under the 2.0 branch

```shell
composer require laravel-admin-ext/latlong:2.x -vvv
```
