### ISSUE TITLE
In production or on CPanel latlong extension does not work. 

### ISSUE THREAD

**Issue by mohsinayoob** [laravel-admin-extensions/latlong#44]
its only working while project is running using php artisan serve.
admin/config.php contains
<img width="832" alt="Screenshot 2021-04-28 at 8 49 16 PM" src="https://user-images.githubusercontent.com/41894237/116433719-35a27500-a863-11eb-9909-2bda943430b6.png">

it always returns `Field type [latlong] does not exist.` while project is hosted on cpanel.
<img width="850" alt="Screenshot 2021-04-28 at 8 46 01 PM" src="https://user-images.githubusercontent.com/41894237/116433865-566aca80-a863-11eb-90f8-456963028d31.png">

**Comment by mohsinayoob** [comment]
It was not working when I was installing fresh packages using composer install on cpanel but putting vendors from local to cpanel fixed the issue.

**Comment by sicaboy** [comment]
> It was not working when I was installing fresh packages using composer install on cpanel but putting vendors from local to cpanel fixed the issue.

Being said that, it might caused by different dependency vendor package was used, because of different php versions between your local and the server.
